version: '3'

services:
  api:
    build: .
    container_name: iot_api
    ports:
      - "8998:3050"
      - "8999:3051"
    depends_on:
      - db
    links:
      - db
    networks:
      - internal
      
  db:
    image: mongo
    container_name: iot_db
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ./volumes/db:/data/db
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=admin
      - MONGO_INIT_DB_ROOT_PASSWORD=admin
    networks:
      - internal

networks:
  internal: