version: '3'

services:
  api:
    build: .
    container_name: iot_api
    ports:
      - "8001:3050"
    depends_on:
      - db
    links:
      - db
    networks:
      - internal
      
  db:
    image: mongo
    container_name: iot_db
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - ~/docker:/data/db
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=admin
      - MONGO_INIT_DB_ROOT_PASSWORD=admin
    networks:
      - internal

  # mongo-express:
  #   image: mongo-express
  #   container_name: iot_db_manager
  #   depends_on:
  #     - db
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=db
  #     - ME_CONFIG_MONGODB_PORT=28017
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
  #   networks:
  #     - internal


networks:
  internal: